---
# tasks file for Jenkins

- name: Build Jenkins | Configure Vagrantfile
  include: buildVagrant.yml
  when: not user_infrastructure

- name: Deploy Jenkins | Vagrant Up
  include: deployvagrant.yml
  when: not user_infrastructure

- name:  Destroy Jenkin |  Vagrant Destroy
  include: vagrantdestroy.yml
  when: destroy == "yes" and not user_infrastructure
